sudo: required
services:
    - docker

before_install:
    - docker build -t aalandril/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run aalandril/react-test npm test -- --coverage

after_success:
    - docker build -t aalandril/multi-client ./client
    - docker build -t aalandril/multi-nginx ./nginx
    - docker build -t aalandril/multi-server ./server
    - docker build -t aalandril/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push aalandril/multi-client
    - docker push aalandril/multi-nginx 
    - docker push aalandril/multi-server
    - docker push aalandril/multi-worker

    deploy:
        provider: elasticbeanstalk
        region: eu-west-1
        app: multi-docker
        env: MultiDocker-env
        bucket_name: elasticbeanstalk-eu-west-1-686651145759
        bucket_path: docker-multi
        on:
            branch: master
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key: $AWS_SECRET_KEY
